name: Generate test programs

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  build:
    name: Build on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]

    steps:
      - name: Checkout your code
        uses: actions/checkout@v4

      - name: Set up MSVC (Windows)
        if: runner.os == 'Windows'
        uses: ilammy/msvc-dev-cmd@v1

      - name: Download cJSON files
        working-directory: hpcflow/data/programs/hello_world
        run: |
          mkdir cJSON
          curl -sSL https://raw.githubusercontent.com/DaveGamble/cJSON/master/cJSON.c -o cJSON/cJSON.c
          curl -sSL https://raw.githubusercontent.com/DaveGamble/cJSON/master/cJSON.h -o cJSON/cJSON.h
        shell: bash

      - name: Build program
        working-directory: hpcflow/data/programs/hello_world
        run: |
          gcc hello_world.c cJSON/cJSON.c -I cJSON -o hello_world
        shell: bash

      - name: Run program (optional)
        working-directory: hpcflow/data/programs/hello_world
        run: |
          echo '{ "p1": 10, "p2": 20, "p3": 30 }' > input.json
          ./hello_world input.json output.json
          cat output.json
        shell: bash

      - name: Upload `hello_world` artifact
        uses: actions/upload-artifact@v4
        with:
          name: hello_world_${{ matrix.os }}${{ matrix.os == 'Windows' && '.exe' || '' }}
          path: hpcflow/data/programs/hello_world/hello_world*
