name: Test shells
concurrency:
  | # e.g. don't run simultaneously on the same branch (since we may commit to that branch)
  ci-test-shells-${{ format('{0}github.head_ref', 'refs/heads') || github.ref }}

env:
  PYTHON_VERSION: "3.12"
  POETRY_VERSION: "2.1.3"

on:
  workflow_dispatch: # manual invocation
    inputs:
      tmate_debugging:
        description: "Enable tmate debugging (https://github.com/marketplace/actions/debugging-with-tmate)"
        required: true
        default: false
        type: boolean

jobs:
  test-wsl:
    runs-on: windows-latest
    steps:
      - uses: Vampire/setup-wsl@v7 # install a WSL distribution
      - uses: actions/checkout@v6
        with:
          ref: ${{ github.ref }}
      - name: Setup tmate session
        if: inputs.tmate_debugging == 'true'
        uses: mxschmitt/action-tmate@v3
        with:
          detached: true          
      - uses: actions/setup-python@v6
        with:
          python-version: ${{ env.PYTHON_VERSION }}
      - uses: hpcflow/github-support/setup-poetry@main
        with:
          version: ${{ env.POETRY_VERSION }}
      - uses: hpcflow/github-support/init-cache@main
        with:
          name: wsl-test
          version: ${{ env.PYTHON_VERSION }}

      - name: Install dependencies
        run: poetry install --without dev,pyinstaller

      - name: Run WSL tests
        run: |
          poetry run hpcflow test --wsl

      - name: Upload all pytest temp dirs
        if: always()
        uses: actions/upload-artifact@v6
        with:
          name: pytest-temp-mtex
          path: /tmp/pytest-of-*
          retention-days: 1
