name: Test shells
concurrency:
  | # e.g. don't run simultaneously on the same branch (since we may commit to that branch)
  ci-test-shells-${{ format('{0}github.head_ref', 'refs/heads') || github.ref }}

env:
  PYTHON_VERSION: "3.12"
  POETRY_VERSION: "2.1.3"

on:
  workflow_dispatch: # manual invocation

jobs:
  test-wsl:
    runs-on: windows-latest
    steps:
      - uses: Vampire/setup-wsl@v6 # install a WSL distribution
      - uses: actions/checkout@v5
        with:
          ref: ${{ github.ref }}
      - uses: actions/setup-python@v6
        with:
          python-version: ${{ env.PYTHON_VERSION }}
      - uses: hpcflow/github-support/setup-poetry@main
        with:
          version: ${{ env.POETRY_VERSION }}
      - uses: hpcflow/github-support/init-cache@main
        with:
          name: wsl-test
          version: ${{ env.PYTHON_VERSION }}

      - name: Install dependencies
        run: poetry install --without dev,pyinstaller

      - name: Configure hpcflow for WSL
        run: |
          poetry run hpcflow config update --json shells.wsl.defaults '{\"WSL_executable\": \"wsl.exe\"}'
          poetry run hpcflow config add-scheduler direct_posix
      - name: Run WSL tests
        run: |
          poetry run hpcflow test --wsl
