name: typecheck
env:
  POETRY_VERSION: "1.4"
on: push
jobs:
  run-mypy:
    # Note that we only do this on one platform and with the earliest reasonable Python
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [ "3.12" ]
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Init Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install and configure poetry ${{ env.POETRY_VERSION }}
        uses: ./.github/actions/setup-poetry
        with:
          version: ${{ env.POETRY_VERSION }}
      - name: Cache Virtual Environment
        uses: actions/cache@v4
        with:
          path: ./.venv
          key: ${{ runner.os }}-typecheck-${{ matrix.python-version }}-venv-${{ hashFiles('**/poetry.lock') }}
      - name: Install Dependencies
        run: |
          poetry install --without dev,pyinstaller --with typecheck
      - name: Perform Type Check
        run: |
          poetry run mypy hpcflow
